### ISSUE TITLE
Update markup of templates to Bootstrap 4

### ISSUE THREAD

**Issue by santonelli** [plone/plone.app.z3cform#113]
Due to #2967 we have to update the markup of the templates listed below. 

- [x] plone.app.z3cform.templates.form.pt
- [x] plone.app.z3cform.templates.layout.pt
- [x] plone.app.z3cform.templates.macros.pt
- [x] plone.app.z3cform.templates.singlecheckboxbool_display.pt
- [x] plone.app.z3cform.templates.singlecheckboxbool_hidden.pt
- [x] plone.app.z3cform.templates.singlecheckboxbool_input.pt
- [x] plone.app.z3cform.templates.widget.pt

Follow bootstrap markup, for example `input type submit` should be `button type submit`.
Check z3c.form if overrides are needed there.

Feel free to add missing templates here. See also #3061 for further details. Check overrides in [plonetheme.tokyo](https://github.com/collective/plonetheme.tokyo) for already existing updated templates.

**Comment by agitator** [comment]
Field elements should follow bootstrap order
<img width="739" alt="Screenshot 2020-08-06 at 11 04 47" src="https://user-images.githubusercontent.com/365761/89513325-b486e780-d7d4-11ea-8edd-e69fbfb3b529.png">

Add html required attribute
<img width="759" alt="Screenshot 2020-08-06 at 11 05 45" src="https://user-images.githubusercontent.com/365761/89513415-d1231f80-d7d4-11ea-984c-bc5644c3d06e.png">

Support for fallback or alternative validation messages
Error message should stay under input field
<img width="742" alt="Screenshot 2020-08-06 at 11 06 55" src="https://user-images.githubusercontent.com/365761/89513582-0891cc00-d7d5-11ea-98f4-de54ff5298d4.png">


Example markup in Products.CMFPlone.controlpanel.browser.redirects-controlpanel.pt

**Comment by agitator** [comment]
also some issues with primary/secondary classes on https://github.com/plone/Products.CMFPlone/issues/3080

**Comment by petschki** [comment]
latest commits fix `required` attribute and markup order ... the issue with button classes is solved for dexterty add/edit forms in general, but other z3c forms (eg. login) need to have an `updateActions()` method to set the classes correctly ...

**Comment by agitator** [comment]
Thx @petschki
