### ISSUE TITLE
AjaxSelectFieldWidget throwing Javascript error with non-string values

### ISSUE THREAD

**Issue by NicolasGoeddel** [plone/plone.app.z3cform#120]
Hi,
I am using the [`AjaxSelectFieldWidget`](https://github.com/plone/plone.app.z3cform/blob/a6d579446177c886fdba9c3e3edd8cf31996130d/plone/app/z3cform/widget.py#L891) together with a `zope.schema.List` field and the `value_type=zope.schema.Choice`. The source for that `Choice` field is a vocabulary consisting of terms with `int` values, `str` token and `str` titles. The reason is that I want a list of integers in the end.

When opening the edit form of a content using this field and I try to write something into the field I get a endless spinning icon:
![image](https://user-images.githubusercontent.com/1520064/98669267-73611f00-2351-11eb-834f-f99386188c21.png)
Also I can see the following error in the browser's console:
![image](https://user-images.githubusercontent.com/1520064/98669360-91c71a80-2351-11eb-84f0-5e25bfc406dd.png)
Which seems to happen in this function:
![image](https://user-images.githubusercontent.com/1520064/98669453-b28f7000-2351-11eb-809b-4e5660fd5bdd.png)

Somehow the `id` is an integer which makes no sense. I don't know how the whole thing works but I guess the `id` should be the `token` and not the `value` of the `SimpleTerm` instance. Because the token always is a string and the value could be anything, even a `datetime` object or just anything else. I think it would make even more sense if the `title` was used instead of the `value` or the `token` because it could be translated to the correct language using i18n.

Here is the example field:
```python
    directives.widget(testfield=AjaxSelectFieldWidget)
    testfield = schema.List(
        title=_("testfield"),
        description=_("Test field"),
        required=False,
        value_type=schema.Choice(
            vocabulary=SimpleVocabulary([SimpleTerm(1, '1', 'Eins'), SimpleTerm(2, '2', 'Zwei')])
        )
    )
```

**Comment by jensens** [comment]
I am pretty sure I fixed this with https://github.com/plone/plone.app.z3cform/pull/104
