### ISSUE TITLE
HTML in form description

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.z3cform#138]
Is there a reason why we should not use HTML in form description ?

Before [this commit](https://github.com/plone/plone.app.z3cform/commit/8701e64b204c4659fdc13f72053bccdaf88c8908#diff-ffe82e8acb25550744b5552c31503ea171be431c05a8d51864f532fb177e1b16), it was possible.

But now, `structure` has been removed:
https://github.com/plone/plone.app.z3cform/blob/9e6b82f1b896b0d2206826da8f9747584d117dc0/plone/app/z3cform/templates/form.pt#L14

**Comment by laulaz** [comment]
@petschki @agitator can I have your input on this ?  🙏

**Comment by petschki** [comment]
this war removed by accident. I'll add it again.

**Comment by laulaz** [comment]
Great, thanks @petschki ❤️
