### ISSUE TITLE
Cannot set a relative URL in link widget

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.z3cform#160]
Relative URLs are no longer accepted by the browser in the link widget, because of the use of `type="url"`input (see commit 4903a79 @thet).

You can test it on Plone 6 demo site, by [creating a link](https://classic.demo.plone.org/en/++add++Link) and trying to use relative URL : 

<img width="997" alt="capture" src="https://user-images.githubusercontent.com/1101273/224301421-fefb264b-abe6-4cbf-9c84-d6ac5870919b.png">

I think we should come back to `type="text"` input, because playing with patterns validation might be too complex.
I will propose a PR for that 👍

**Comment by thet** [comment]
@laulaz I'd prefer to do something like that:

https://stackoverflow.com/a/42566065/1337474

**Comment by laulaz** [comment]
@thet from what I tried, patterns validation cannot validate relative URLs with `type="url"` input.

This works and validates both http URLs and relative URLs (rejecting invalid URLs like `http:/plone.org`) :
```
<input type="text" pattern="(https?://|/).*"  />
```

This does not accept any relative URLs : 
```
<input type="url" pattern="(https?://|/).*"  />
```

You can try it there : https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_pattern6

So, can we switch back to a `type="text"` input with validation pattern ?  or do you have any solution to keep the `type="url"` input ?

**Comment by thet** [comment]
@laulaz I can confirm. No luck when using `type="url"` with a pattern attribute.
Let's switch back to type="text+

**Comment by thet** [comment]
@laulaz can you make a PR?‌ I'd include the pattern attribute. For a relative links you'd also need to allow `../` kind of links.

**Comment by thet** [comment]
We can of course use no validation at all in this case...

How do the container internal URLs look like? I guess you mean something like Docker container, right? Wouldn't they also have a http:// included?

**Comment by laulaz** [comment]
@thet no, I meant the Plone container (folder), for example if you have 
```
folder/
 ├─ my-content
 ├─ my-link
```
and want to insert a link in `my-link` to `my-content` 😉   so, without any `../` or `/`or whatever.

**Comment by thet** [comment]
you're right. that sounds like a `type="text"` without any pattern attribute.

**Comment by thet** [comment]
One more question: why wouldn't you use the "Internal" reference link feature when linking to content on the same site?

**Comment by laulaz** [comment]
> One more question: why wouldn't you use the "Internal" reference link feature when linking to content on the same site?

You're right, in most case, it should be enough.

But 2 things :
1. the field help text says we can use it for relative URLs
2. we already had customers with site "parts" referring to other technologies (ex: domain.com/whoiswho for their contact list, managed in PHP). If they have multiple domains, you can't use "Internal" reference link neither External full address. But relative address works. You can imagine other usecases like redirection URLs, etc.
