### ISSUE TITLE
p.a.widgets dependency?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.z3cform#19]
According to @jensens https://github.com/plone/plone.app.widgets/issues/98#issuecomment-88097762 p.a.widgets got merged into here on commit https://github.com/plone/plone.app.z3cform/commit/6eb2ebd4b7f9232e95ad96455d4483d4b3c06eab

Still p.a.z3cform master depends on p.a.widgets on, setup.py, metadata.xml, top-level configure.zcml and also a test (plone/app/z3cform/tests/test_widgets.py) and on widgets.py.

So does p.a.widgets need to be used on plone 5 or should this package be fixed?

**Comment by vangheem** [comment]
plone.app.widgets package still exists in plone 5 is a base package. All the final widgets were merged into other plone core packages but there was too much logic that was shared between Archetypes and z3cform widgets that didn't fit in any other intermediary package so we needed to keep plone.app.widgets in a stripped down form to provide some utilities and other bases.

https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/widget.py#L4 for example

Unless someone has a better idea for where all the shared logic between Archetypes and z3cform widgets should go?

**Comment by mauritsvanrees** [comment]
Meanwhile we are at Plone 6, so Archetypes is dead. Is it time to pick this up again? It sounds like `plone.app.widgets` could be merged to `plone.app.z3cform`.  I don't know this part of Plone well, so have no idea if this is a sane idea. But one package less seems good.

@thet do you have an opinion here?

Grepping for `plone.app.widgets` in Plone core, ignoring code in tests:

- 10 translations in `plone.app.locales`
- `Products.CMFPlone` imports `utils.get_relateditems_options`
- `plone.app.content` imports `utils.get_datetime_options`
- `plone.app.z3c.form` includes its zcml and imports various items in `widget.py` 
- `plone.app.relationfield` uses it in `widget.zcml`, but looking at the zcml conditions this seems not used in Plone 6.
- `plone.app.dexterity` only uses it in backwards compatibility code:

```
try:
    from plone.app.z3cform.interfaces import IFieldPermissionChecker
except ImportError:
    # bbb for < plone 5.2rc2
    from plone.app.widgets.interfaces import IFieldPermissionChecker
```

**Comment by jensens** [comment]
Probably safe, but I would do a in-depth dependency check before to not add transitive recursive dependencies on Python or ZCML level.

**Comment by thet** [comment]
I have to think this through - I also always wanted to get rid of this package, also much of it's responsibilities are spread over the whole codebase. plone.app.z3cform would be a good fit. But for generic JavaScript widget configuration, which could also be used in a non-z3cform context, plone.app.z3cform is semantically not the right package.
If we change this for Plone 6 we should get this right and probably discuss this in detail and come up with a good plan.

**Comment by jensens** [comment]
IIRC the generic one is `plone.z3cform`?

**Comment by petschki** [comment]
I've grepped through the code today:

<img width="505" alt="Bildschirm­foto 2022-11-30 um 08 42 18" src="https://user-images.githubusercontent.com/511761/204736369-b366ca38-bf39-4a5a-adac-2e7c828ad40a.png">

Suggestions:

* move the `plone.app.widgets.utils` methods to the already existing `Products.CMFPlone.patterns.utils` and fix the imports ... 
* the import in `plone.app.dexterity` is only for backwards compatibility and can be removed
* move `dict_merge` from base to utils above
* move the base widget classes to `plone.app.z3cform`

with this `plone.app.widgets` can be removed safely ... I could take care about that these days, but this is probably too late for 6.0 final?

**Comment by gforcada** [comment]
By all means 6.1 IMHO, if we can move all the code and leave it marked as deprecated 👍🏾

**Comment by jensens** [comment]
> move the plone.app.widgets.utils methods to the already existing Products.CMFPlone.patterns.utils and fix the imports ...

I think then we get circular imports. I would suggest `plone.z3cform` or `plonebase` for those. If there is one one usage, move it into the package where it is used/ 

> the import in plone.app.dexterity is only for backwards compatibility and can be removed

+1

> move dict_merge from base to utils above

see above ;)

> move the base widget classes to plone.app.z3cform

+1

**Comment by petschki** [comment]
I've set up a todo list what needs to be done https://github.com/plone/plone.app.widgets/issues/220

**Comment by mauritsvanrees** [comment]
I would do that for 6.1.

**Comment by petschki** [comment]
current state of https://github.com/plone/plone.app.z3cform/pull/155 and https://github.com/plone/plone.app.widgets/pull/221 is safe to merge and release, because it simply moves code to the new place without the need of updating other packages. Though the minor versions should be bumpted according to `semver` because of new backwards compatible public API changes.

**Comment by mauritsvanrees** [comment]
I like the direction, but not the timing, so short before the second release candidate. :-/
It would be nice to get rid of another package (which we don't yet do here), but that is also something we *cannot* do in the release candidate stage. So we don't yet gain anything. This is probably fine for the core packages if the tests pass, but I see mostly danger that we overlook something and break add-ons.

**Comment by petschki** [comment]
I'm totally d'accord with you @mauritsvanrees  ... as @thet mentioned there is pattern configuration code in CMFPlone too and it makes sense to think about this too in this refactoring.
