### ISSUE TITLE
 Missing support to constrain allowed content types.

### ISSUE THREAD

**Issue by thet** [plone/plone.app.z3cform#198]
We can restrict the allowed content types for file inputs on upload time on the client side like so:

```
<input type="file" name="file" accept="audio/mp3, audio/flac" />
```

or:

```
<input type="file" name="image" accept="image/*" />
```

this package is currently missing support for that.

Related:
- https://github.com/plone/plone.namedfile/issues/157
- https://github.com/plone/plone.namedfile/pull/158
- https://github.com/plone/plone.formwidget.namedfile/issues/66
- https://github.com/plone/plone.formwidget.namedfile/pull/67

**Comment by mauritsvanrees** [comment]
I have released plone.namedfile 6.3.0 and have updated the versions/constraints on https://dist.plone.org/release/6.0-dev/ and https://dist.plone.org/release/6.1-dev/
So the checks should pass now.

**Comment by thet** [comment]
Fixed with: https://github.com/plone/plone.app.z3cform/pull/200 and https://github.com/plone/plone.app.z3cform/pull/199
