### ISSUE TITLE
Why deprecate WysiwygWidget ?

### ISSUE THREAD

**Issue by gotcha** [plone/plone.app.z3cform#31]
https://github.com/plone/plone.app.z3cform/commit/33e8cb8f3059dd21732e9023d215d7e481437a23 deprecates WysiwygWidget.

I think it is a useful widget when you want to edit an html string without the transform/mimetype support. To store HTML in the registry for instance.

Is there another reason to deprecate it than the fact it is not used by Plone core ?

**Comment by sunew** [comment]
It's a little confusing with several wysiwyg widgets. Couldn't the needed feature be made configurable on RichTextFieldWidget ?

**Comment by jensens** [comment]
This one is outdated and probably not relevant anymore. Reopen if I am wrong.
