### ISSUE TITLE
Related items dataconverter issue with schema.Choice _type

### ISSUE THREAD

**Issue by cillianderoiste** [plone/plone.app.z3cform#57]
I've been using the schema below for a mosaic tile and noticed that when I upgraded from plone 5.0 to 5.1a2 (p.a.z3cform 2.1) I get the following error when I try to save the tile:

```
  File "/srv/mysite/eggs/plone.app.z3cform-2.1-py2.7.egg/plone/app/z3cform/converters.py", line 268, in <genexpr>
    return collectionType(valueType(v) for v in value)
TypeError: 'NoneType' object is not callable
```

My understanding is that https://github.com/plone/plone.app.z3cform/commit/ea8aea41dd7c19466c857662ac7687a3bb0c427e#diff-ed4c6111d877ee2923ee59437d512519R267 expects the field's value_type._type to be callable, but for vocabularies _type is None.

Am I doing it wrong, or is this a more general issue?

The Schema definition:
```
class IQuotes(model.Schema):
    form.widget(item_uids=RelatedItemsFieldWidget)
    item_uids = schema.List(
        title=u"Select quotes",
        required=False,
        default=[],
        value_type=schema.Choice(
            source=CatalogSource(portal_type='Quote'),
        ),
    )
```

**Comment by cillianderoiste** [comment]
I see @datakurre has already opened a PR which fixes this: plone/plone.app.z3cform#58

**Comment by jensens** [comment]
merged
