### ISSUE TITLE
RichTextWidget options broken in non-contentish context

### ISSUE THREAD

**Issue by petschki** [plone/plone.app.z3cform#66]
as discovered in https://github.com/plone/plone.app.widgets/pull/163 the RichTextWidget doesn't pass the correct context to `get_tinymce_options`. @thet fixes this issue with this pr https://github.com/plone/plone.app.widgets/pull/160, but I think it would be better to fix in this package ... any thoughts? @davisagli

**Comment by thet** [comment]
Fixed via: https://github.com/plone/plone.app.z3cform/pull/68
