### ISSUE TITLE
Make all fieldset labels translatable 

### ISSUE THREAD

**Issue by mtrebron** [plone/plone.app.z3cform#87]
For dexterity content types with multiple fieldsets, only the default fieldset label and those provided by behaviors like "Categorization" or "Settings" are being translated in the content type's edit view.

This is likely due to missing `i18n:translate="" i18n:domain="plone"` in the legend element of the macros.pt template.

https://github.com/plone/plone.app.z3cform/blob/master/plone/app/z3cform/templates/macros.pt#L118

**Comment by mtrebron** [comment]
The i18n domain can be as far up as the titlelessform macro, no effect otherwise:

´´´
            <metal:define  i18n:domain="plone" define-macro="titlelessform">
´´´

**Comment by jensens** [comment]
Is this still an issue in Plone 6? AFAIK this is no longer a problem.

**Comment by mtrebron** [comment]
I will take a look in the next few days

**Comment by mtrebron** [comment]
Yes this is still an issue.

To quickly replicate:

1. Start Plone with `debug-mode on`
2. Create Plone 6 classic site
3. Install Multilingual
4. Edit Dexterity Page type to add:
```   
    <fieldset name="new_fieldset" label="label_new_fieldset" description="A new fieldset for custom fields">
      <field name="a_new_field" type="zope.schema.TextLine">
        <description>This is a new field</description>
        <required>False</required>
        <title>A new field</title>
      </field>
    </fieldset>
```
5. Add msgid and msgstr entries to collective/plone.app.locales in the languages to test with, e.g. en and de
```
/usr/local/Plone/venv/lib/python3.9/site-packages/plone/app/locales/locales/de/LC_MESSAGES/de/plone.po
msgid "label_new_fieldset"
msgstr "Neue Fieldset"

/usr/local/Plone/venv/lib/python3.9/site-packages/plone/app/locales/locales/de/LC_MESSAGES/en/plone.po
msgid "label_new_fieldset"
msgstr "New Fieldset"
```
6. Restart the server to recompile the .po files
7. Create a Page and notice that the fieldset label is untranslated.
8. insert `i18n:translate="" i18n:domain="plone"` on line 128 of 
/usr/local/Plone/venv/lib/python3.9/site-packages/plone/app/z3cform/templates/macros.pt
9. Reload the page and notice how the label now shows its translation

**Comment by mtrebron** [comment]
Just adding `i18n:translate=""` will do
